### ISSUE TITLE
Facebook Permissions

### ISSUE THREAD

**Issue by tpharaoh** [rubenwouters/crm-launcher#6]
Can you give a short guide as to what kind of permissions facebook needs?

When I auth:ed it, it said I didn't give enough. So, I tried again, and it seems I need to submit the app to be allowed to post/etc

**Comment by rubenwouters** [comment]
Did you de-select any of the permissions in the process?

**Comment by rubenwouters** [comment]
Note that you **don't** need to submit your Facebook app to use it for CRM Launcher. 

Here you can see the permissions that you need to grant:
https://youtu.be/Tgo_EzEDppg

Hope this helps.

**Comment by tpharaoh** [comment]
no, set to web, and saved...

**Comment by rubenwouters** [comment]
Can you confirm that you see and grant the same permissions as shown in the video?

**Comment by tpharaoh** [comment]
I don't have those options

**Comment by rubenwouters** [comment]
I need more details to be able to help you. Maybe send me a screencast of your flow?

**Comment by tpharaoh** [comment]
email it to you here via git?

Its really straightforward...

**Comment by rubenwouters** [comment]
You should be able to grant following permissions:
- Publish pages
- Manage pages
- Read page mailboxes

If you get an error message saying you've not given enough permissions one of these three permissions weren't granted. In case you have specific questions don't hesitate to contact me.

**Comment by tpharaoh** [comment]
From _v2.0_ https://developers.facebook.com/docs/apps/changelog onwards,
the permissions other than public_profile, email and the user_friends need
to the submitted for review before you can make your app_live_; until then,
only the testers/admin/developers of the app will be able to test app with
those permissions.

from stackoverflow... so I guess thats it

**Comment by rubenwouters** [comment]
Indeed. You have to log in with an account who has admin or developer role on the page you're linking and grant access from that account. I should state that in the docs more clear, indeed. Thanks for noticing.

**Comment by tpharaoh** [comment]
I think that was the issue... misconfigured page ID.

**Comment by rubenwouters** [comment]
Good to hear. Up and running now? :)

**Comment by tpharaoh** [comment]
seems to be.

BTW, I know its bad practice, but since I have another admin tool
installed, I used their roles. So, I added in constructor of the publish
and user pages to check the role and if not send a 401. Is there a way to
override it without editing it your code directly.

Love your crmlauncher

**Comment by rubenwouters** [comment]
Can't help you with that, I'm sorry. 

Roles will be included in one of the next versions.
